title: Sana Fessuh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring data scientist with a creative edge. Majoring in Data Science with a minor in Media Arts and Design at The University Of Chicago. Blending analytical skills with artistic vision to derive unique insights from data.Focusing on machine learning techniques, data analytics, and data visualization with principles of design and media studies. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
